




development:
  adapter: postgresql
  database: starwar_development
  pool: 5
  timeout: 5000
 

test:
  adapter: postgresql
  database: starwar_test
  pool: 5
  timeout: 5000
 
production:
  adapter: postgresql
  database: starwar_production
  pool: 5
  timeout: 5000